### ISSUE TITLE
"{cm-*}" triggers exception

### ISSUE THREAD

**Issue by nippur72** [EgonOlsen71/basicv2#28]
This line of code triggers a Java exception:
```
1 print "{cm-*}"
```
```
Running assembler...
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 0
        at java.lang.String.charAt(Unknown Source)
        at com.sixtyfour.parser.assembly.AssemblyParser.getBinaryData(AssemblyParser.java:249)
        at com.sixtyfour.Assembler.compile(Assembler.java:206)
        at com.sixtyfour.cbmnative.shell.MoSpeedCL.main(MoSpeedCL.java:201)
```

`cm-asterisk` does work though.

**Comment by EgonOlsen71** [comment]
Should be fixed now. It was treating the * as an indicator for the multiple occurance of a character, not as a character itself.
